name: lean's openwrt from dyc

on:
  push:
    branches:
      - master
    paths:
      - 'actionStart_dyc'
  schedule:
    - cron: '00 04 * * 5'

env:
  TZ: Asia/Shanghai

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.repository == 'msylgj/NanoPi-R2S-OpenWrt'

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          curl https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh  | sed '/#/d' | sed 's/\\//g' | sed 's/exit 0//g' | sed 's/sudo apt -y install//g' | sed 's/sudo apt-get -y install//g' | sed 's/:i386//g' | xargs sudo apt-get -y --no-install-recommends install
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk

      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/

      - name: Init Source
        run: |
          mkdir friendlywrt-rk3328
          cd friendlywrt-rk3328
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.1 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle --depth=1
          repo sync -c --no-tags --no-clone-bundle -j8
          cd friendlywrt/ && git fetch --unshallow

      - name: Patch Kernel
        run: |
          . ./scripts/patch_kernel_5.4.sh

      - name: Load Package seed
        run: |
          cd friendlywrt-rk3328
          . ../scripts/remove_unused_config.sh
          cat configs/config_rk3328 | grep "TARGET" >> ../config/base_rk3328_dyc.seed
          cat ../config/app_config_dyc.seed >> ../config/base_rk3328_dyc.seed
          cat ../config/base_rk3328_dyc.seed > configs/config_rk3328

      - name: Merge
        run: |
          cd friendlywrt-rk3328/friendlywrt
          git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
          git remote add upstream https://github.com/coolsnowwolf/lede && git fetch upstream
          git rebase adc1a9a3676b8d7be1b48b5aed185a94d8e42728^ --onto upstream/master -X theirs
          git revert --no-edit 23378ed9a481dc73923f5bfa81637a1a8056882d
          git revert --no-edit 4787dbaf3cad44b374b660cc0fef9386963e6795
          git revert --no-edit 463b6ac0508de4788a6e41335471ced0a255e1cd
          git revert --no-edit 8faac30089ce616940b3e96c4f4d900aeb6b9fcb
          git revert --no-edit db6a03f2565b162ca63a4cb8af9d90bad5406f29
          git checkout upstream/master -- feeds.conf.default
          sed -i '5s/#src-git/src-git/g' feeds.conf.default
          #sed -i '$a\src-git helloworld https://github.com/fw876/helloworld' feeds.conf.default
          git apply ../../patches/002-enable-autocore.patch

      - name: Mods
        run: |
          cd friendlywrt-rk3328/friendlywrt/package/lean/
          rm -rf luci-theme-argon
          git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git
          cd ../../
          sed -i "s/OpenWrt/Built by OPoA($(date +%Y.%m.%d)) @ OpenWrt/g" package/lean/default-settings/files/zzz-default-settings
          sed -i "/FriendlyWRT/a\ OPoA Build" package/base-files/files/etc/banner
          sed -i '/uci commit luci/i\uci set luci.main.mediaurlbase="/luci-static/argon"' package/lean/default-settings/files/zzz-default-settings
          sed -i '/exit/i\find /etc/rc.d/ -name *docker* -delete' package/lean/default-settings/files/zzz-default-settings
          sed -i '/uci commit luci/a\uci commit firewall' package/lean/default-settings/files/zzz-default-settings
          sed -i '/uci commit luci/a\uci set firewall.@zone[1].forward=REJECT' package/lean/default-settings/files/zzz-default-settings
          sed -i '/uci commit luci/a\uci set firewall.@zone[1].input=REJECT' package/lean/default-settings/files/zzz-default-settings
          sed -i '/uci commit luci/a\uci commit network' package/lean/default-settings/files/zzz-default-settings
          sed -i '/uci commit luci/a\uci delete network.lan.ip6assign' package/lean/default-settings/files/zzz-default-settings
          sed -i '/uci commit luci/a\uci delete network.wan6' package/lean/default-settings/files/zzz-default-settings
          sed -i '/uci commit luci/a\uci commit dropbear' package/lean/default-settings/files/zzz-default-settings
          sed -i '/uci commit luci/a\uci set dropbear.@dropbear[0].Interface='lan'' package/lean/default-settings/files/zzz-default-settings
          sed -i '/distfeeds/i\sed -i '/target/d' /etc/opkg/distfeeds.conf' package/lean/default-settings/files/zzz-default-settings
          sed -i '/distfeeds/i\sed -i '/helloworld/d' /etc/opkg/distfeeds.conf' package/lean/default-settings/files/zzz-default-settings
          mv ../../scripts/checkwan.sh package/base-files/files/bin && sed -i '/exit/i\/bin/sh /bin/checkwan.sh 1>/dev/null 2>&1 &' package/base-files/files/etc/rc.local
          mv ../../scripts/autoupdate_tracker.sh package/base-files/files/usr/bin && chmod +x package/base-files/files/usr/bin/autoupdate_tracker.sh
          mv ../../scripts/autoupdate.sh package/base-files/files/root/au.sh && chmod +x package/base-files/files/root/au.sh

      # 互换wan&lan口,需要的话删除下面四行前面#号即可
      #- name: Swap wan and lan
      #  run: |
      #    cd friendlywrt-rk3328/friendlywrt
      #    git apply ../../patches/003-openwrt-swap-wan-and-lan.patch

      - name: Add OPKG Feeds
        run: |
          cd friendlywrt-rk3328
          git clone -b src --depth 1 https://github.com/songchenwen/nanopi-r2s-opkg-feeds.git
          mkdir -p friendlywrt/package/base-files/files/etc/opkg/keys/
          cp nanopi-r2s-opkg-feeds/keys/* friendlywrt/package/base-files/files/etc/opkg/keys/
          rm -rf nanopi-r2s-opkg-feeds
          echo "grep -qF 'songchenwen.com' /etc/opkg/customfeeds.conf || echo 'src/gz r2s_targets_scw https://songchenwen.com/nanopi-r2s-opkg-feeds/packages' >> /etc/opkg/customfeeds.conf" >> friendlywrt/package/base-files/files/root/setup.sh

      - name: Build FriendlyWrt
        run: |
          cd friendlywrt-rk3328
          ./build.sh nanopi_r2s.mk

      - name: Fix FriendlyWrt rootfs owner and group
        run: |
          sudo df -lh
          lodev=$(sudo losetup -f)
          echo "found unused loop dev $lodev"
          sudo losetup -P ${lodev} $lodev friendlywrt-rk3328/out/*.img
          sudo rm -rf /mnt/friendlywrt-tmp
          sudo mkdir -p /mnt/friendlywrt-tmp
          sudo mount ${lodev}p1 /mnt/friendlywrt-tmp
          sudo chown -R root:root /mnt/friendlywrt-tmp
          sudo umount /mnt/friendlywrt-tmp
          sudo losetup -d ${lodev}

      - name: Zip Files
        run: |
          gzip friendlywrt-rk3328/out/*.img

      - name: Assemble Artifact
        id: assemble_artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          mv friendlywrt-rk3328/out/*img* ./artifact/
          cp friendlywrt-rk3328/friendlywrt/.config ./artifact/
          zip -r artifact.zip ./artifact/
          release_tag="R2S-OPoA-DYC-$(date +%Y-%m-%d)"
          echo "##[set-output name=release_tag;]$release_tag"

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ steps.assemble_artifact.outputs.release_tag }}-ROM
          path: ./artifact.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.workflow_token }}
        with:
          tag_name: ${{ steps.assemble_artifact.outputs.release_tag }}
          release_name: 自动发布 ${{ steps.assemble_artifact.outputs.release_tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.workflow_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./artifact.zip
          asset_name: ${{ steps.assemble_artifact.outputs.release_tag }}-ROM.zip
          asset_content_type: application/zip
